services:
  - type: web
    name: preethi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn preethi.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: disorder
          property: connectionString
