services:
  - type: web
    name: disorder-service
    env: python
    buildCommand: ""
    startCommand: gunicorn disease_prediction.wsgi
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: True
