services:
  - type: web
    name: preethi-service
    env: python
    buildCommand: pip install -r requirements.txt
    # ← Here’s the magic: migrate, then gunicorn
    startCommand: python manage.py migrate && gunicorn disease_prediction.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: disorder
          property: connectionString
      - key: DEBUG
        value: True
